version: 3.2.0-{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
platform: x86

install:
- cmd: >-
    git clone https://github.com/BrianGladman/mpir.git
    git clone https://github.com/BrianGladman/mpfr.git
    git clone https://github.com/ledger/ledger.git

    # Boost 1.68, 1.69 require CMake 3.13 or newer.
    # Boost 1.70 requires CMake 3.14 or newer.
    # appveyor Windows build environment Visual Studio 2017 has pre-install CMake 3.13.3
    git clone https://github.com/boostorg/boost.git --branch boost-1.69.0 --recursive

    # build static boost libraries
    cd boost
    .\bootstrap.bat
    .\b2.exe link=static runtime-link=static threading=multi --layout=versioned

    cd %APPVEYOR_BUILD_FOLDER%\mpir\msvc\vs15
    .\msbuild.bat gc LIB Win32 Release

    cd %APPVEYOR_BUILD_FOLDER%\mpfr\build.vc15\lib_mpfr
    msbuild /p:Configuration=Release lib_mpfr.vcxproj

    cd %APPVEYOR_BUILD_FOLDER%\ledger
    git checkout v3.2.0

    cmake . -DCMAKE_BUILD_TYPE:STRING="Release" -DBUILD_LIBRARY=OFF -DMPFR_LIB:FILEPATH="../../mpfr/build.vc15/lib/Win32/Release/mpfr" -DGMP_LIB:FILEPATH="../../mpir/lib/win32/Release/mpir" -DMPFR_PATH:PATH="../mpfr/lib/Win32/Release" -DGMP_PATH:PATH="../mpir/lib/win32/Release" -DBUILD_DOCS:BOOL="0" -DHAVE_REALPATH:BOOL="0" -DHAVE_GETPWUID:BOOL="0" -DHAVE_GETPWNAM:BOOL="0" -DHAVE_IOCTL:BOOL="0" -DHAVE_ISATTY:BOOL="0" -DBOOST_ROOT:PATH="../boost/" -DBoost_USE_STATIC_LIBS:BOOL="1" -DCMAKE_CXX_FLAGS_RELEASE:STRING="/MT /Zi /Ob0 /Od" -G "Visual Studio 15"

    msbuild /p:Configuration=Release src\ledger.vcxproj

build: off

artifacts:
- path: ledger\Release
  name: ledger-v$(appveyor_build_version)

# Publishing artifacts to GitHub Releases
deploy:
- provider: GitHub
  auth_token:
    secure: h3hUgrslQ+hReA3meF2fVnfEsxceOub8bXm2ub0/Hcy8yys6TAOHgp+p2d9871Ef
  release: ledger-v$(appveyor_build_version)
  description: ledger-v$(appveyor_build_version)
  artifact: ledger-v$(appveyor_build_version)
  draft: true
  force_update: true
