version: 3.1.3-{build}
skip_branch_with_pr: true
image: Visual Studio 2017
platform: x86
install:
- cmd: >-
    git clone https://github.com/BrianGladman/mpir.git

    git clone https://github.com/BrianGladman/mpfr.git

    git clone https://github.com/ledger/ledger.git

    git clone https://github.com/boostorg/boost.git --branch boost-1.69.0 --recursive


    cd boost

    .\bootstrap.bat

    .\b2.exe link=static runtime-link=static threading=multi --layout=versioned


    cd %APPVEYOR_BUILD_FOLDER%\mpir\msvc\vs15

    .\msbuild.bat gc LIB Win32 Release


    cd %APPVEYOR_BUILD_FOLDER%\mpfr\build.vc15\lib_mpfr

    msbuild /p:Configuration=Release lib_mpfr.vcxproj


    cd %APPVEYOR_BUILD_FOLDER%\ledger

    git checkout v3.1.3


    cmake . -DCMAKE_BUILD_TYPE:STRING="Release" -DBUILD_LIBRARY=OFF -DMPFR_LIB:FILEPATH="../../mpfr/build.vc15/lib/Win32/Release/mpfr" -DGMP_LIB:FILEPATH="../../mpir/lib/win32/Release/mpir" -DMPFR_PATH:PATH="../mpfr/lib/Win32/Release" -DGMP_PATH:PATH="../mpir/lib/win32/Release" -DBUILD_DOCS:BOOL="0" -DHAVE_REALPATH:BOOL="0" -DHAVE_GETPWUID:BOOL="0" -DHAVE_GETPWNAM:BOOL="0" -DHAVE_IOCTL:BOOL="0" -DHAVE_ISATTY:BOOL="0" -DBOOST_ROOT:PATH="../boost/" -DBoost_USE_STATIC_LIBS:BOOL="1" -DCMAKE_CXX_FLAGS_RELEASE:STRING="/MT /Zi /Ob0 /Od" -G "Visual Studio 15"


    msbuild /p:Configuration=Release src\ledger.vcxproj


    copy Release\ledger.exe %APPVEYOR_BUILD_FOLDER%


    cd %APPVEYOR_BUILD_FOLDER%


    7z a ledger.zip ledger.exe

    appveyor PushArtifact ledger.zip
build:
  publish_wap: true
  verbosity: normal
artifacts:
- path: ledger.zip